SampleCRM/SampleCRM/Models/TableModels/MaintenanceFeeClearance.cs
using SampleCRM.Models.Base;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleCRM.Models.TableModels
{
    /// <summary>
    /// 保守料消込
    /// </summary>
    [Table( "T_MaintenanceFeeClearances" )]
    public class MaintenanceFeeClearance : TransactionBase
    {
        [Key]
        [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
        [Display( Name = "消込コード" )]
        [Comment( "消込コード" )]
        public int ClearanceCode { get; set; }

        [Display( Name = "消込入金日" )]
        [Comment( "消込入金日" )]
        [Precision( 0 )]
        [DataType( DataType.Date )]
        public DateTime? ClearanceDepositDate { get; set; }

        [Required]
        [Display( Name = "消込額" )]
        [Comment( "消込額" )]
        public int ClearanceAmount { get; set; }

        [Display( Name = "消込入力日" )]
        [Comment( "消込入力日" )]
        [Precision( 0 )]
        [DataType( DataType.Date )]
        public DateTime? ClearanceInputDate { get; set; }

        [Display( Name = "振込番号" )]
        [Comment( "振込番号" )]
        public int? TransferNumber { get; set; }
    }
}

SampleCRM/SampleCRM/Controllers/MaintenanceFeeClearanceController.cs
using SampleCRM.Contexts;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SampleCRM.Controllers
{
    public class MaintenanceFeeClearanceController : Controller
    {
        private readonly SampleCRMContext _context;

        public MaintenanceFeeClearanceController( SampleCRMContext context )
        {
            _context = context;
        }

        // GET: MaintenanceFeeClearanceController
        public ActionResult Index()
        {
            return View();
        }

        // GET: MaintenanceFeeClearanceController/Details/5
        public async Task<ActionResult> Details( int? id )
        {
            if ( id == null || await _context.MaintenanceFeeClearances.FindAsync( id ) is not { } maintenanceFeeClearance )
            {
                return NotFound();
            }

            return View( new MaintenanceFeeClearanceListItemViewModel( maintenanceFeeClearance ) );
        }

        // GET: MaintenanceFeeClearanceController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MaintenanceFeeClearanceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }

        // GET: MaintenanceFeeClearanceController/Edit/5
        public ActionResult Edit( int id )
        {
            return View();
        }

        // POST: MaintenanceFeeClearanceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( int id, IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }

        // GET: MaintenanceFeeClearanceController/Delete/5
        public ActionResult Delete( int id )
        {
            return View();
        }

        // POST: MaintenanceFeeClearanceController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete( int id, IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }
    }
}

SampleCRM/SampleCRM/Views/MaintenanceFeeClearance/Details.cshtml
@model SampleCRM.Models.ViewModels.MaintenanceFeeClearanceListItemViewModel

@{
    ViewData["Title"] = "消込情報詳細";
}

<h1>消込情報詳細</h1>

<div>
    <hr />
    <dl class="row table-striped">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClearanceCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClearanceCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClearanceDepositDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClearanceDepositDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClearanceAmount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClearanceAmount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClearanceInputDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClearanceInputDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TransferNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TransferNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ClearanceCode">消込情報修正</a> |
    <a asp-controller="MaintenanceFeeClearance" asp-action="Details" asp-route-id="@Model.ClearanceCode">契約情報詳細へ戻る</a>
</div>