SampleCRM/SampleCRM/Controllers/DataManagementController.cs
using SampleCRM.Common;
using SampleCRM.Contexts;
using SampleCRM.Identity;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using System.Net.Mime;
using System.Runtime.Versioning;
using System.Text;

namespace SampleCRM.Controllers
{
    [Authorize( Policy = nameof( AuthorizationPolicies.AnyRolePolicy ) )]
    // for GetSampleFormatString
    [SupportedOSPlatform( "windows" )]
    public class DataManagementController : Controller
    {
        private readonly SampleCRMContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public DataManagementController( SampleCRMContext context, IWebHostEnvironment hostingEnvironment )
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: DataManagementController
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 画面上からInsertMastersを実行
        /// </summary>
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public ActionResult InsertMasters()
        {
            SeedData.SeedData.InsertMasters( _context );

            return RedirectToAction( nameof( Index ) );
        }

        /// <summary>
        /// 画面上からスキーマの削除および再作成
        /// </summary>
        /// <remarks>
        /// 全テーブルのAUTO_INCREMENTを一斉にリセットする方法が不明なため、スキーマ自体を削除したのち再作成して疑似的にリセットを実現している。
        /// </remarks>
        // TODO: デプロイ時にはこのメソッドを消す。（全データが消えるので運用開始後に間違えて実行するとまずい。）
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public ActionResult ResetSchema()
        {
            var rdc = (RelationalDatabaseCreator)_context.GetService<IDatabaseCreator>();

            rdc.EnsureDeleted(); // スキーマ削除
            _context.Database.EnsureCreated(); // スキーマ作成
            SeedData.SeedData.InsertIdentities( _context );

            return RedirectToAction( nameof( Index ) );
        }

        // データが多いとForm間での受け渡しが現実的でなかったので
        private async Task<SelectList> GetCompanySelectList()
        {
            // 営業会社一覧取得(コードと名前だけ)
            var companies = await _context.Companies
                .Where( x => !x.IsClientCompany )
                .OrderBy( x => x.CompanyCode )
                .Select( x => new { x.CompanyCode, x.CompanyName } )
                .ToListAsync();
            return new SelectList( companies, "CompanyCode", "CompanyName" );
        }        

        /// <summary>
        /// ファイルダウンロード
        /// </summary>
        public ActionResult DownloadFile( string filePath )
        {
            return File(
                System.IO.File.ReadAllBytes( filePath ),
                MediaTypeNames.Application.Octet,
                DateTime.Now.ToString( "yyyy年MM月dd日HH時mm分ss秒" ) + ".xlsx" );
        }
    }
}

SampleCRM/SampleCRM/Controllers/MaintenanceFeeController.cs
using SampleCRM.Contexts;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SampleCRM.Controllers
{
    public class MaintenanceFeeController : Controller
    {
        private readonly SampleCRMContext _context;

        public MaintenanceFeeController( SampleCRMContext context )
        {
            _context = context;
        }

        // GET: MaintenanceFeeController
        public ActionResult Index()
        {
            return View();
        }

        // GET: MaintenanceFeeController/Details/5
        public async Task<ActionResult> Details( int? id )
        {
            if ( id == null || await _context.MaintenanceFees.FindAsync( id ) is not { } maintenanceFee )
            {
                return NotFound();
            }

            return View( new MaintenanceFeeListItemViewModel( maintenanceFee ) );
        }

        // GET: MaintenanceFeeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MaintenanceFeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }

        // GET: MaintenanceFeeController/Edit/5
        public ActionResult Edit( int id )
        {
            return View();
        }

        // POST: MaintenanceFeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( int id, IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }

        // GET: MaintenanceFeeController/Delete/5
        public ActionResult Delete( int id )
        {
            return View();
        }

        // POST: MaintenanceFeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete( int id, IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }
    }
}

SampleCRM/SampleCRM/Controllers/OrderController.cs
using DocumentFormat.OpenXml.Drawing.Charts;
using SampleCRM.Contexts;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SampleCRM.Controllers
{
    public class OrderController : Controller
    {
        private readonly SampleCRMContext _context;

        public OrderController( SampleCRMContext context )
        {
            _context = context;
        }

        // GET: OrderController
        public ActionResult Index()
        {
            return View();
        }

        // GET: OrderController/Details/5
        public async Task<ActionResult> Details( int? id )
        {
            if ( id is null )
            {
                return NotFound();
            }

            var viewModel = await ( from Order in _context.Orders
                                    join DeliveryStatus in _context.DeliveryStatuses on Order.DeliveryStatusCode equals DeliveryStatus.DeliveryStatusCode
                                    join ClientEmployeeToOrder in _context.ClientEmployeeToOrders on Order.OrderCode equals ClientEmployeeToOrder.OrderCode
                                    join ClientEmployee in _context.Employees on ClientEmployeeToOrder.EmployeeCode equals ClientEmployee.EmployeeCode
                                    join SalesEmployeeToOrder in _context.SalesEmployeeToOrders on Order.OrderCode equals SalesEmployeeToOrder.OrderCode
                                    join SalesEmployee in _context.Employees on SalesEmployeeToOrder.EmployeeCode equals SalesEmployee.EmployeeCode
                                    join orderToPayment in _context.OrderToPayments on Order.OrderCode equals orderToPayment.OrderCode into groupJoinnedOrderToPayments
                                    from OrderToPayment in groupJoinnedOrderToPayments.DefaultIfEmpty()
                                    join Payment in _context.Payments on OrderToPayment.PaymentCode equals Payment.PaymentCode into groupJoinnedPayments
                                    from Payment in groupJoinnedPayments.DefaultIfEmpty()
                                    join PaymentMethod in _context.PaymentMethods on Payment.PaymentMethodCode equals PaymentMethod.PaymentMethodCode into groupJoinnedPaymentMethods
                                    from PaymentMethod in groupJoinnedPaymentMethods.DefaultIfEmpty()
                                    where Order.OrderCode == id
                                    select new OrderDetailsViewModel( Order, DeliveryStatus, ClientEmployee, SalesEmployee, Payment, PaymentMethod ) )
                                    .SingleOrDefaultAsync();

            if ( viewModel is null )
            {
                return NotFound();
            }

            viewModel.ContractList = new ContractListViewModel(
                await ( from Contract in _context.Contracts
                        join ContractStatus in _context.ContractStatuses on Contract.ContractStatusCode equals ContractStatus.ContractStatusCode
                        join UpdateMethod in _context.UpdateMethods on Contract.UpdateMethodCode equals UpdateMethod.UpdateMethodCode
                        join SystemKind in _context.SystemKinds on Contract.SystemKindCode equals SystemKind.SystemKindCode
                        join CDShippingDepartment in _context.Departments on Contract.CDShippingDepartmentCode equals CDShippingDepartment.DepartmentCode into groupJoinnedCDShippingDepartments
                        from CDShippingDepartment in groupJoinnedCDShippingDepartments.DefaultIfEmpty()
                        join ContractToSystemLicense in _context.ContractToSystemLicenses on Contract.ContractCode equals ContractToSystemLicense.ContractCode into groupJoinnedContractToSystemLicense
                        from ContractToSystemLicense in groupJoinnedContractToSystemLicense.DefaultIfEmpty()
                        join SystemLicense in _context.SystemLicenses on ContractToSystemLicense.SystemLicenseCode equals SystemLicense.SystemLicenseCode into groupJoinnedSystemLicenses
                        from SystemLicense in groupJoinnedSystemLicenses.DefaultIfEmpty()
                        join ContractToDataLicense in _context.ContractToDataLicenses on Contract.ContractCode equals ContractToDataLicense.ContractCode into groupJoinnedContractToDataLicenses
                        from ContractToDataLicense in groupJoinnedContractToDataLicenses.DefaultIfEmpty()
                        join DataLicense in _context.DataLicenses on ContractToDataLicense.DataLicenseCode equals DataLicense.DataLicenseCode into groupJoinnedDataLicense
                        from DataLicense in groupJoinnedDataLicense.DefaultIfEmpty()
                        where Contract.OrderCode == id
                        select new ContractListItemViewModel(
                            Contract,
                            ContractStatus,
                            UpdateMethod,
                            SystemKind,
                            CDShippingDepartment,
                            SystemLicense,
                            DataLicense
                        ) ).ToListAsync() )
            {
                OrderCode = viewModel.OrderCode
            };

            viewModel.MaintenanceFeeBillList = await ( from MaintenanceFee in _context.MaintenanceFees
                                                       join maintenanceFeeToBill in _context.MaintenanceFeeToBills on MaintenanceFee.MaintenanceFeeCode equals maintenanceFeeToBill.MaintenanceFeeCode into groupJoinnedMaintenanceFeeToBills
                                                       from MaintenanceFeeToBill in groupJoinnedMaintenanceFeeToBills.DefaultIfEmpty()
                                                       join MaintenanceFeeBill in _context.MaintenanceFeeBills on MaintenanceFeeToBill.BillCode equals MaintenanceFeeBill.BillCode into groupJoinnedMaintenanceFeeBills
                                                       from MaintenanceFeeBill in groupJoinnedMaintenanceFeeBills.DefaultIfEmpty()
                                                       join BillingDepartment in _context.Departments on MaintenanceFeeBill.BillingDepartmentCode equals BillingDepartment.DepartmentCode into groupJoinnedBillingDepartments
                                                       from BillingDepartment in groupJoinnedBillingDepartments.DefaultIfEmpty()
                                                       join maintenanceFeeBillToClearance in _context.MaintenanceFeeBillToClearances on MaintenanceFeeBill.BillCode equals maintenanceFeeBillToClearance.BillCode into groupJoinnedMaintenanceFeeBillToClearances
                                                       from MaintenanceFeeBillToClearance in groupJoinnedMaintenanceFeeBillToClearances.DefaultIfEmpty()
                                                       join MaintenanceFeeClearance in _context.MaintenanceFeeClearances on MaintenanceFeeBillToClearance.ClearanceCode equals MaintenanceFeeClearance.ClearanceCode into groupJoinnedMaintenanceFeeClearances
                                                       from MaintenanceFeeClearance in groupJoinnedMaintenanceFeeClearances.DefaultIfEmpty()
                                                       join ContractToMaintenanceFee in _context.ContractToMaintenanceFees on MaintenanceFee.MaintenanceFeeCode equals ContractToMaintenanceFee.MaintenanceFeeCode
                                                       join Contract in _context.Contracts on ContractToMaintenanceFee.ContractCode equals Contract.ContractCode
                                                       join Order in _context.Orders on Contract.OrderCode equals Order.OrderCode
                                                       where Order.OrderCode == id
                                                       orderby MaintenanceFeeBill.BillingDate descending
                                                       group new
                                                       {
                                                           MaintenanceFee,
                                                           MaintenanceFeeBill,
                                                           BillingDepartment,
                                                           MaintenanceFeeClearance
                                                       } by MaintenanceFeeBill.BillCode into grouped
                                                       select new MaintenanceFeeBillListItemViewModel(
                                                           grouped.Select( x => x.MaintenanceFee ).OrderBy( x => x.MaintenanceStartDate ).ToList(),
                                                           grouped.Single().MaintenanceFeeBill,
                                                           grouped.Single().BillingDepartment,
                                                           grouped.Select( x => x.MaintenanceFeeClearance ).OrderBy( x => x.ClearanceDepositDate ).ToList() )
                                          ).ToListAsync();


            return View( viewModel );
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( IFormCollection collection )
        {
            try
            {
                return RedirectToAction( nameof( Index ) );
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit( int id )
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( int id, IFormCollection collection )
        {
            try
            {

SampleCRM/SampleCRM/Controllers/RoleController.cs
using SampleCRM.Identity;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IdentityRole = SampleCRM.Models.TableModels.IdentityRole;


namespace SampleCRM.Controllers
{
    /// <summary>
    /// ロール一覧ページのController
    /// </summary>
    [Authorize( Policy = nameof( AuthorizationPolicies.UserAdministratorPolicy ) )]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> RoleManager { get; }

        public RoleController( RoleManager<IdentityRole> roleManager ) => RoleManager = roleManager;

        /// <summary>
        /// ロール一覧画面
        /// </summary>
        /// <returns></returns>
        /// <remarks>Get: Role/Index</remarks>
        public async Task<IActionResult> Index()
            => View( await RoleManager.Roles.OrderBy( x => x.Id ).Select( x => new RoleViewModel( x ) ).ToListAsync() );
    }
}

SampleCRM/SampleCRM/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@using static SampleCRM.Identity.AuthorizationPolicies
@using IdentityUser = SampleCRM.Models.TableModels.IdentityUser;

@inject IAuthorizationService AuthorizationService
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleCRM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/multichoise.css" asp-append-version="true" />
    <!-- import the included stylesheet for some (very basic) default styling -->
    <link rel="stylesheet" href="~/css/PagedList.css" asp-append-version="true" />
    <!-- ヘッダー色の設定（Local：緑系、Development：青系、ほか：黒系） -->
    <environment names="Local">
        <style>
            #navigationBar {
                background-color: #009900 !important;
            }
        </style>
    </environment>
    <environment names="Development">
        <style>
            #navigationBar {
                background-color: #000099 !important;
            }
        </style>
    </environment>
</head>
<body>
    <header>
        <nav id="navigationBar" class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color: #333333">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">SampleCRM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if ((await AuthorizationService.AuthorizeAsync(User, nameof(AnyRolePolicy))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="ClientCompany" asp-action="Index">●顧客会社情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="SalesCompany" asp-action="Index">●営業会社情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="Index">☓発注情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Contract" asp-action="Index">☓契約情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="License" asp-action="Index">☓ライセンス情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="MaintenanceFeeBill" asp-action="Index">☓保守料請求情報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white">☓検索</a>
                                </li>
                            }
                            @if ((await AuthorizationService.AuthorizeAsync(User, nameof(GlobalAdministratorOnlyPolicy))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white">☓監査ログ</a>
                                </li>
                            }
                            @if ((await AuthorizationService.AuthorizeAsync(User, nameof(AnyRolePolicy))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="DataManagement" asp-action="Index">▲管理メニュー</a>
                                </li>
                            }
                            @if ((await AuthorizationService.AuthorizeAsync(User, nameof(UserAdministratorPolicy))).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">●ユーザー管理</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Role" asp-action="Index">●ロール一覧</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SampleCRM
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--for YubinBango-->
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <script src="~/js/samplepostal.js"></script>
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SampleCRM/SampleCRM/Views/Shared/_MaintenanceFeeBillListPartial.cshtml
@using SampleCRM.Models.ViewModels;

@model IEnumerable<MaintenanceFeeBillListItemViewModel>

<h3>保守料情報一覧</h3>

<div>
    <hr />
    @if (!Model.Any() || Model.First() is not { } firstMaintenanceFeeBill)
    {
        <text><b>保守料情報が登録されていません</b></text>
    }
    else
    {
        @foreach (var item in Model.Select((Value, Index) => new { Value, Index }))
        {
            <div>

                <h4>保守料情報 @(item.Index + 1)</h4>
                <table class="table" style="vertical-align:middle">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(_ => item.Value.MaintenanceFees.First().MaintenanceFeePrice)
                            </th>
                            <th>
                                @Html.DisplayNameFor(_ => item.Value.MaintenanceFees.First().MaintenanceStartDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(_ => item.Value.MaintenanceFees.First().MaintenanceEndDate)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var maintenanceFee in item.Value.MaintenanceFees)
                        {
                            <tr>
                                <td>@maintenanceFee.MaintenanceFeePrice</td>
                                <td>@maintenanceFee.MaintenanceStartDate</td>
                                <td>@maintenanceFee.MaintenanceEndDate</td>
                                <td>
                                    <div>
                                        <a asp-controller="MaintenanceFee" asp-action="Details" asp-route-id="@maintenanceFee.MaintenanceFeeCode">詳細</a>
                                    </div>
                                    <div>
                                        <a asp-controller="MaintenanceFee" asp-action="Edit" asp-route-id="@maintenanceFee.MaintenanceFeeCode">修正</a>
                                    </div>
                                    <div>
                                        <a asp-controller="MaintenanceFee" asp-action="Delete" asp-route-id="@maintenanceFee.MaintenanceFeeCode">削除</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <h4>請求情報 @(item.Index + 1)</h4>
                @if (item.Value is not { } maintenanceFeeBill || maintenanceFeeBill.BillingDate is null)
                {
                    <text><b>請求情報が未設定です</b></text>
                }
                else
                {
                    <table class="table" style="vertical-align:middle">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeBill.BillingDepartmentName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeBill.BillingDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeBill.BillingAmount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeBill.TotalDepositAmount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeBill.BillingDifferenceAmount)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <td>@maintenanceFeeBill.BillingDepartmentName</td>
                                <td>@maintenanceFeeBill.BillingDate</td>
                                <td>@maintenanceFeeBill.BillingAmount</td>
                                <td>@maintenanceFeeBill.TotalDepositAmount</td>
                                <td class="@(maintenanceFeeBill.BillingDifferenceAmount < 0 ? "negative" : "")">@maintenanceFeeBill.BillingDifferenceAmount</td>
                                <td>
                                    <div>
                                        <a asp-controller="MaintenanceFeeBill" asp-action="Details" asp-route-id="@maintenanceFeeBill.BillCode">詳細</a>
                                    </div>
                                    <div>
                                        <a asp-controller="MaintenanceFeeBill" asp-action="Edit" asp-route-id="@maintenanceFeeBill.BillCode">修正</a>
                                    </div>
                                    <div>
                                        <a asp-controller="MaintenanceFeeBill" asp-action="Delete" asp-route-id="@maintenanceFeeBill.BillCode">削除</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }

                <h4>消込情報 @(item.Index + 1)</h4>
                @if (!item.Value.MaintenanceFeeClearances.Any() || item.Value.MaintenanceFeeClearances.First() is not { } firstMaintenanceFeeClearance)
                {
                    <text><b>消込情報が登録されていません</b></text>
                }
                else
                {
                    <table class="table" style="vertical-align:middle">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeClearance.ClearanceDepositDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(_ => firstMaintenanceFeeClearance.ClearanceAmount)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var maintenanceFeeClearance in item.Value.MaintenanceFeeClearances)
                            {
                                <tr>
                                    <td>@maintenanceFeeClearance.ClearanceDepositDate</td>
                                    <td>@maintenanceFeeClearance.ClearanceAmount</td>
                                    <td>
                                        <div>
                                            <a asp-controller="MaintenanceFeeClearance" asp-action="Details" asp-route-id="@maintenanceFeeClearance.ClearanceCode">詳細</a>
                                        </div>
                                        <div>
                                            <a asp-controller="MaintenanceFeeClearance" asp-action="Edit" asp-route-id="@maintenanceFeeClearance.ClearanceCode">修正</a>
                                        </div>
                                        <div>
                                            <a asp-controller="MaintenanceFeeClearance" asp-action="Delete" asp-route-id="@maintenanceFeeClearance.ClearanceCode">削除</a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }

            </div>
        }
    }
</div>