SampleCRM/SampleCRM/Models/ViewModels/SalesDepartment.cs
using System.ComponentModel.DataAnnotations;

namespace SampleCRM.Models.ViewModels
{
    public class SalesDepartment
    {

        // 契約会社関連情報
        [Key]
        [Display( Name = "会社コード" )]
        public int CompanyCode { get; set; }

        [Display( Name = "会社名" )]
        public string CompanyName { get; set; }

        [Display( Name = "会社名カナ" )]
        public string CompanyPhoneticName { get; set; }

        // 部署関連情報

        // 部署コードはAutoincrement属性のため部署テーブルには登録不要だが
        // DisplayOrderと紐づける事と担当者テーブルに登録するために取得の必要はある
        public int DepartmentCode { get; set; }

        // 代表部署かどうかを編集できるか
        public bool EditableMainDepartment { get; set; }

        [Required]
        [Display( Name = "代表部署" )]
        public bool IsMainDepartment { get; set; }

        [Required( ErrorMessage = "部署名は必須です。" )]
        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [Display( Name = "部署名" )]
        public string DepartmentName { get; set; }

        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [RegularExpression( @"\A[ァ-ヶ ー]+\z", ErrorMessage = "全角カタカナのみ入力できます。" )]
        [Display( Name = "部署名カナ" )]
        public string PhoneticName { get; set; }

        [StringLength( 8, ErrorMessage = "8文字まで" )]
        [DataType( DataType.PostalCode )]
        [RegularExpression( @"\d{3}-\d{4}", ErrorMessage = "○○○-○○○○で記述してください。" )]
        [Display( Name = "部署の郵便番号" )]
        public string PostalCode { get; set; }

        [StringLength( 64, ErrorMessage = "64文字まで" )]
        [Display( Name = "部署の住所" )]
        public string Address { get; set; }

        //[DataType(DataType.PhoneNumber)]
        [Phone( ErrorMessage = "正しい電話番号ではありません。" )]
        [StringLength( 16, ErrorMessage = "16文字まで" )]
        [Display( Name = "部署の電話番号" )]
        public string TelNumber { get; set; }

        //[DataType(DataType.PhoneNumber)]
        [Phone( ErrorMessage = "正しいFAX番号ではありません。" )]
        [StringLength( 16, ErrorMessage = "16文字まで" )]
        [Display( Name = "部署のFAX番号" )]
        public string FaxNumber { get; set; }

        //[DataType(DataType.EmailAddress)]
        [EmailAddress( ErrorMessage = "正しいメールアドレスではありません。" )]
        [StringLength( 255, ErrorMessage = "255文字まで" )]
        [Display( Name = "部署のメールアドレス" )]
        public string Email { get; set; }

        // 営業担当一覧
        [Display( Name = "営業担当一覧" )]
        public IList<SalesEmployee> Employees { get; set; }
    }
}

SampleCRM/SampleCRM/Controllers/SalesCompanyController.cs
using SampleCRM.Contexts;
using SampleCRM.Identity;
using SampleCRM.Models.TableModels;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SampleCRM.Controllers
{
    [Authorize( Policy = nameof( AuthorizationPolicies.AnyRolePolicy ) )]
    public class SalesCompanyController : Controller
    {
        private readonly SampleCRMContext _context;

        /// <summary>
        /// 営業会社コード開始番号(10億)
        /// </summary>
        private const int ORIGIN_SALES_COMPANY_CODE = 1000000000;

        public SalesCompanyController( SampleCRMContext context )
        {
            _context = context;
        }

        // GET: SalesCompany
        public async Task<IActionResult> Index()
        {
            // 営業会社全て取得
            var companies = await _context.Companies.Where( x => !x.IsClientCompany ).OrderBy( x => x.CompanyCode ).ToListAsync();
            var model = new List<SalesCompany>();
            if ( companies.Any() )
            {
                foreach ( var company in companies )
                {
                    var temp = new SalesCompany();
                    // 会社情報から分かるデータ登録
                    temp.CompanyCode = company.CompanyCode;
                    temp.CompanyName = company.CompanyName;
                    temp.PhoneticName = company.PhoneticName;
                    temp.Note = company.Note;

                    // 代表部署情報の取得
                    var department = await _context.Departments.Where( x => x.CompanyCode == company.CompanyCode && x.IsMain ).FirstOrDefaultAsync();
                    if ( department != null )
                    {
                        // 代表部署の情報登録
                        temp.PostalCode = department.PostalCode;
                        //TODO: 住所関連修正 
                        temp.Address = department.City;
                        temp.TelNumber = department.TelNumber;
                    }
                    model.Add( temp );
                }
            }

            return View( model );
        }

        // GET: SalesCompany/Details/5
        public async Task<IActionResult> Details( int? id )
        {
            if ( id == null || _context.Companies == null || _context.Departments == null )
            {
                return NotFound();
            }

            // 会社情報の取得と登録
            var company = await _context.Companies.FirstOrDefaultAsync( m => m.CompanyCode == id );
            if ( company == null )
            {
                return NotFound();
            }
            var model = new SalesCompany();
            model.CompanyCode = company.CompanyCode;
            model.CompanyName = company.CompanyName;
            model.PhoneticName = company.PhoneticName;
            model.Note = company.Note;

            // 会社コードを持った部署情報を全て取得し登録
            var departments = await _context.Departments.Where( x => x.CompanyCode == company.CompanyCode ).OrderBy( x => x.DisplayOrder ).ToListAsync();
            model.Departments = [];
            foreach ( var department in departments )
            {
                var temp = new SalesDepartment();
                temp.DepartmentCode = department.DepartmentCode;
                temp.IsMainDepartment = department.IsMain;
                temp.DepartmentName = department.DepartmentName;
                temp.PhoneticName = department.PhoneticName;
                temp.PostalCode = department.PostalCode;
                //TODO: 住所関連修正 
                temp.Address = department.City;
                temp.TelNumber = department.TelNumber;
                temp.FaxNumber = department.FaxNumber;
                temp.Email = department.Email;
                model.Departments.Add( temp );
            }

            return View( model );
        }

        // GET: SalesCompany/Create
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public IActionResult Create()
        {
            return View();
        }

        // POST: SalesCompany/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public async Task<IActionResult> Create( [Bind( "CompanyName,PhoneticName,Note" )] SalesCompany model )
        {
            if ( ModelState.IsValid )
            {
                var tableModel = new Company();

                // フォームから登録
                tableModel.CompanyName = model.CompanyName;
                tableModel.PhoneticName = model.PhoneticName;
                tableModel.Note = model.Note;

                //tableModel.UpdateUser = 1;
                //tableModel.UpdateDate = DateTime.Now;

                // 固定値
                tableModel.IsClientCompany = false;
                tableModel.CompanyStatusCode = _context.CompanyStatuses.Single( x => x.CompanyStatusName == "営業会社" ).CompanyStatusCode;  // TODO: 一致無し時・複数一致時はエラーページに飛ばす。

                // 計算で出す
                int tempNum = ORIGIN_SALES_COMPANY_CODE;
                var order = await _context.Companies.Where( x => !x.IsClientCompany ).Select( x => x.CompanyCode ).ToListAsync();
                if ( order.Any() )
                {
                    tempNum = order.Max() + 1;
                }
                tableModel.CompanyCode = tempNum;

                // 追加
                _context.Add( tableModel );
                await _context.SaveChangesAsync();
                return RedirectToAction( nameof( Index ) );
            }
            return View( model );
        }

        // GET: SalesCompany/Edit/5
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public async Task<IActionResult> Edit( int? id )
        {
            if ( id == null || _context.Companies == null )
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync( id );
            if ( company == null )
            {
                return NotFound();
            }

            var model = new SalesCompany();
            model.CompanyCode = (int)id;
            model.CompanyName = company.CompanyName;
            model.PhoneticName = company.PhoneticName;
            model.Note = company.Note;

            return View( model );
        }

        // POST: SalesCompany/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public async Task<IActionResult> Edit( int id, [Bind( "CompanyCode,CompanyName,PhoneticName,Note" )] SalesCompany model )
        {
            if ( id != model.CompanyCode )
            {
                return NotFound();
            }

            if ( ModelState.IsValid )
            {
                var tableModel = await _context.Companies.FindAsync( id );
                tableModel.CompanyName = model.CompanyName;
                tableModel.PhoneticName = model.PhoneticName;
                tableModel.Note = model.Note;
                try
                {
                    _context.Update( tableModel );
                    await _context.SaveChangesAsync();
                }
                catch ( DbUpdateConcurrencyException )
                {
                    if ( !SalesCompanyExists( model.CompanyCode ) )
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction( nameof( Index ) );
            }
            return View( model );
        }

        // GET: SalesCompany/Delete/5
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public async Task<IActionResult> Delete( int? id )
        {
            if ( id == null || _context.Companies == null )
            {
                return NotFound();
            }

            var company = await _context.Companies.FirstOrDefaultAsync( m => m.CompanyCode == id );
            if ( company == null )
            {
                return NotFound();
            }

            var model = new SalesCompany();
            model.CompanyCode = id.Value;
            model.CompanyName = company.CompanyName;
            model.PhoneticName = company.PhoneticName;

            return View( model );
        }

        // POST: SalesCompany/Delete/5
        [HttpPost, ActionName( "Delete" )]
        [ValidateAntiForgeryToken]
        [Authorize( Policy = nameof( AuthorizationPolicies.GlobalAdministratorOnlyPolicy ) )]
        public async Task<IActionResult> DeleteConfirmed( int id )
        {
            if ( _context.Companies == null )
            {
                return Problem( "Entity set 'SampleCRMContext.SalesCompany'  is null." );
            }
            var model = await _context.Companies.FindAsync( id );
            if ( model != null )
            {
                _context.Companies.Remove( model );
            }

            await _context.SaveChangesAsync();
            return RedirectToAction( nameof( Index ) );
        }

        private bool SalesCompanyExists( int id )
        {
            return _context.Companies.Any( e => e.CompanyCode == id );
        }
    }
}

SampleCRM/SampleCRM/Views/SalesDepartment/Create.cshtml
@model SampleCRM.Models.ViewModels.SalesDepartment

@{
    ViewData["Title"] = "営業部署追加";
}

<h1>営業部署追加</h1>
<h5>@Model.CompanyName</h5>
<div class="form-group">
    <label class="control-label"><label class="control-label"><span style="color:#ff0000;">※</span></label>は必須入力項目です。</label>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" class="h-adr">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                @if(Model.EditableMainDepartment)
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" /> @Html.DisplayNameFor(model => model.IsMainDepartment)
                    </label>
                }
                else
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" disabled="disabled" />既に代表部署が登録されているので設定できません
                    </label>
                }
            </div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label><label class="control-label"><span style="color:#ff0000;">※</span></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneticName" class="control-label"></label>
                <input asp-for="PhoneticName" class="form-control" />
                <span asp-validation-for="PhoneticName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control p-postal-code" />
                <input type="hidden" class="p-country-name" value="Japan" />
                <button type="button" class="btn-secondary postal-search">郵便番号から住所を検索する</button>
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control p-region p-locality p-street-address p-extended-address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelNumber" class="control-label"></label>
                <input asp-for="TelNumber" class="form-control" />
                <span asp-validation-for="TelNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaxNumber" class="control-label"></label>
                <input asp-for="FaxNumber" class="form-control" />
                <span asp-validation-for="FaxNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CompanyCode" />
            <input type="hidden" asp-for="CompanyName" />
            <input type="hidden" asp-for="CompanyPhoneticName" />
            <input type="hidden" asp-for="EditableMainDepartment" />
            <div class="form-group">
                <input type="submit" value="追加" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="SalesCompany" asp-action="Details" asp-route-id="@Model.CompanyCode">営業会社詳細(部署一覧)へ戻る</a>
</div>

SampleCRM/SampleCRM/Views/SalesDepartment/Delete.cshtml
@model SampleCRM.Models.ViewModels.SalesDepartment

@{
    ViewData["Title"] = "営業部署削除";
}

<h1>営業部署削除</h1>
<h5>
    <ruby>
        @Model.CompanyName
        <rt>@Model.CompanyPhoneticName</rt>
    </ruby>
</h5>
<br />
<b>この部署を削除しますか？</b>
<div>※注意：部署に所属する営業担当がいる場合は、先にそちらを削除して下さい。</div>
<div>　　　　また、削除後は復旧できません。</div>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.DepartmentName)
                <rt>@Html.DisplayFor(model => model.PhoneticName)</rt>
            </ruby>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsMainDepartment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsMainDepartment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FaxNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FaxNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompanyCode" />
        <input type="submit" value="削除" class="btn btn-danger" /> |
        <a asp-controller="SalesCompany" asp-action="Details" asp-route-id="@Model.CompanyCode">営業会社詳細(部署一覧)へ戻る</a>
    </form>
</div>

SampleCRM/SampleCRM/Views/SalesDepartment/Details.cshtml
@model SampleCRM.Models.ViewModels.SalesDepartment

@{
    ViewData["Title"] = "営業部署詳細(営業担当者一覧)";
}

<h1>営業部署詳細(営業担当者一覧)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.CompanyName)
                <rt>
                    @Html.DisplayFor(model => model.CompanyPhoneticName)
                </rt>
            </ruby>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.DepartmentName)
                <rt>
                    @Html.DisplayFor(model => model.PhoneticName)
                </rt>
            </ruby>
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FaxNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FaxNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    <!-- ここから営業担当一覧 -->
    <h3>営業担当一覧</h3>
    <p>
        <a asp-controller="SalesEmployee" asp-action="Create" asp-route-id="@Model.DepartmentCode">営業担当追加</a>
    </p>
    <div>
        <hr />
        @if(!Model.Employees.Any())
        {
            <text><b>営業担当が登録されていません</b></text>
        }
        else
        {
            <table class="table" style="vertical-align:middle">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Employees[0].EmployeeName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employees[0].Position)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employees[0].CellPhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employees[0].Email)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var employee in Model.Employees)
                    {
                        <tr>
                            <td>
                                <ruby>
                                    @Html.DisplayFor(modelItem => employee.EmployeeName)
                                    <rt>@Html.DisplayFor(modelItem => employee.PhoneticName)</rt>
                                </ruby>
                            </td>
                            <td>@employee.Position</td>
                            <td>@employee.CellPhoneNumber</td>
                            <td>@employee.Email</td>
                            <td>
                                <a asp-controller="SalesEmployee" asp-action="Details" asp-route-id="@employee.EmployeeCode">詳細</a> | 
                                <a asp-controller="SalesEmployee" asp-action="Edit" asp-route-id="@employee.EmployeeCode">修正</a> | 
                                <a asp-controller="SalesEmployee" asp-action="Delete" asp-route-id="@employee.EmployeeCode">削除</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model.DepartmentCode">営業部署情報修正</a> |
    <a asp-controller="SalesCompany" asp-action="Details" asp-route-id="@Model.CompanyCode">営業会社詳細(部署一覧)へ戻る</a>
</div>

SampleCRM/SampleCRM/Views/SalesDepartment/Edit.cshtml
@model SampleCRM.Models.ViewModels.SalesDepartment

@{
    ViewData["Title"] = "営業部署修正";
}

<h1>営業部署修正</h1>
<h5>
    <ruby>
        @Model.CompanyName
        <rt>@Model.CompanyPhoneticName</rt>
    </ruby>
</h5>
<div class="form-group">
    <label class="control-label"><label class="control-label"><span style="color:#ff0000;">※</span></label>は必須入力項目です。</label>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="h-adr">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                @if(Model.EditableMainDepartment)
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" /> @Html.DisplayNameFor(model => model.IsMainDepartment)
                    </label>
                }
                else
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" disabled="disabled" />既に代表部署が登録されているので設定出来ません
                    </label>
                }
            </div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label><label class="control-label"><span style="color:#ff0000;">※</span></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneticName" class="control-label"></label>
                <input asp-for="PhoneticName" class="form-control" />
                <span asp-validation-for="PhoneticName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control p-postal-code" />
                <input type="hidden" class="p-country-name" value="Japan" />
                <button type="button" class="btn-secondary postal-search">郵便番号から住所を検索する</button>
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control p-region p-locality p-street-address p-extended-address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelNumber" class="control-label"></label>
                <input asp-for="TelNumber" class="form-control" />
                <span asp-validation-for="TelNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaxNumber" class="control-label"></label>
                <input asp-for="FaxNumber" class="form-control" />
                <span asp-validation-for="FaxNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CompanyCode" />
            <input type="hidden" asp-for="CompanyName" />
            <input type="hidden" asp-for="CompanyPhoneticName" />
            <input type="hidden" asp-for="DepartmentCode" />
            <div class="form-group">
                <input type="submit" value="更新" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="SalesCompany" asp-action="Details" asp-route-id="@Model.CompanyCode">営業会社詳細(部署一覧)へ戻る</a>
</div>

SampleCRM/SampleCRM/Views/SalesDepartment/Index.cshtml
@model IEnumerable<SampleCRM.Models.ViewModels.SalesDepartment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyPhoneticName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsMainDepartment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneticName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaxNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyPhoneticName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsMainDepartment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneticName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaxNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CompanyCode">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CompanyCode">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CompanyCode">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>