SampleCRM/SampleCRM/Models/ViewModels/ClientDepartmentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SampleCRM.Models.ViewModels
{
    /// <summary>
    /// 顧客会社用部署情報
    /// 担当者とは1対1の関係
    /// </summary>
    public class ClientDepartmentViewModel
    {
        // 契約会社関連情報
        [Display( Name = "会社コード" )]
        public int CompanyCode { get; set; }

        [Display( Name = "会社名" )]
        public string CompanyName { get; set; }

        [Display( Name = "会社名カナ" )]
        public string CompanyPhoneticName { get; set; }

        // 代表部署かどうかを編集できるか
        public bool EditableMainDepartment { get; set; }

        // 部署関連情報

        // 部署コードはAutoincrement属性のため部署テーブルには登録不要だが
        // DisplayOrderと紐づける事と担当者テーブルに登録するために取得の必要はある
        public int DepartmentCode { get; set; }

        [Required]
        [Display( Name = "代表部署かどうか" )]
        public bool IsMainDepartment { get; set; }

        [Required( ErrorMessage = "部署名は必須です。" )]
        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [Display( Name = "部署名" )]
        public string DepartmentName { get; set; }

        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [RegularExpression( @"\A[ァ-ヶ ー]+\z", ErrorMessage = "全角カタカナのみ入力できます。" )]
        [Display( Name = "部署名カナ" )]
        public string DepartmentPhoneticName { get; set; }

        [StringLength( 8, ErrorMessage = "8文字まで" )]
        [DataType( DataType.PostalCode )]
        [RegularExpression( @"\d{3}-\d{4}", ErrorMessage = "○○○-○○○○で記述してください。" )]
        [Display( Name = "部署の郵便番号" )]
        public string DepartmentPostalCode { get; set; }

        [StringLength( 64, ErrorMessage = "64文字まで" )]
        [Display( Name = "部署の住所" )]
        public string DepartmentAddress { get; set; }

        //[DataType(DataType.PhoneNumber)]
        [Phone( ErrorMessage = "正しい電話番号ではありません。" )]
        [StringLength( 16, ErrorMessage = "16文字まで" )]
        [Display( Name = "部署の電話番号" )]
        public string DepartmentTelNumber { get; set; }

        //[DataType(DataType.PhoneNumber)]
        [Phone( ErrorMessage = "正しいFAX番号ではありません。" )]
        [StringLength( 16, ErrorMessage = "16文字まで" )]
        [Display( Name = "部署のFAX番号" )]
        public string DepartmentFaxNumber { get; set; }

        //[DataType(DataType.EmailAddress)]
        [EmailAddress( ErrorMessage = "正しいメールアドレスではありません。" )]
        [StringLength( 255, ErrorMessage = "255文字まで" )]
        [Display( Name = "部署のメールアドレス" )]
        public string DepartmentEmail { get; set; }

        [Display( Name = "備考" )]
        [StringLength( 2048 )]
        [DataType( DataType.MultilineText )]
        public string Note { get; set; }

        // 部署コードと同じ値に設定する
        // SHOW TABLE STATUS LIKE 'Departments' を実行し、Auto_increment列の値が次の値となるのでそれを挿入する
        [Required]
        [Display( Name = "表示順" )]
        public int DepartmentDisplayOrder { get; set; }


        // 担当者関連情報

        // 外部キーである部署コードは登録の際に部署のインスタンスを登録すればOK
        // 担当者コードについても部署コードと同じ理屈で取得の必要がある

        public int EmployeeCode { get; set; }

        [Required]
        [Display( Name = "代表担当者かどうか" )]
        public bool IsMainEmployee { get; set; }

        [Required( ErrorMessage = "担当者名は必須です。" )]
        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [Display( Name = "担当者名" )]
        public string EmployeeName { get; set; }

        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [RegularExpression( @"^[ァ-ヶ|\-|ー]+$", ErrorMessage = "全角カタカナのみ入力できます。" )]
        [Display( Name = "担当者名カナ" )]
        public string EmployeePhoneticName { get; set; }

        [StringLength( 32, ErrorMessage = "32文字まで" )]
        [Display( Name = "担当者役職" )]
        public string EmployeePosition { get; set; }

        //[DataType(DataType.PhoneNumber)]
        [Phone( ErrorMessage = "正しい電話番号ではありません。" )]
        [StringLength( 16, ErrorMessage = "16文字まで" )]
        [Display( Name = "担当者電話番号" )]
        public string EmployeeTelNumber { get; set; }

        //[DataType(DataType.EmailAddress)]
        [EmailAddress( ErrorMessage = "正しいメールアドレスではありません。" )]
        [StringLength( 255, ErrorMessage = "255文字まで" )]
        [Display( Name = "担当者メールアドレス" )]
        public string EmployeeEmail { get; set; }

        [StringLength( 255, ErrorMessage = "255文字まで" )]
        [Display( Name = "担当者SNSアカウント" )]
        public string EmployeeSNS { get; set; }

        // 担当者コードと同じ値に設定する
        // SHOW TABLE STATUS LIKE 'Departments' を実行し、Auto_increment列の値が次の値となるのでそれを挿入する
        [Required]
        [Display( Name = "表示順" )]
        public int EmployeeDisplayOrder { get; set; }
    }
}

SampleCRM/SampleCRM/Controllers/ClientCompanyController.cs
using DocumentFormat.OpenXml.InkML;
using SampleCRM.Common;
using SampleCRM.Contexts;
using SampleCRM.Identity;
using SampleCRM.Models.Enums;
using SampleCRM.Models.TableModels;
using SampleCRM.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using X.PagedList.EF;
using Company = SampleCRM.Models.TableModels.Company;

namespace SampleCRM.Controllers
{
    [Authorize( Policy = nameof( AuthorizationPolicies.AnyRolePolicy ) )]
    public class ClientCompanyController : Controller
    {
        private SampleCRMContext SampleCRMContext { get; }

        // 会社状態の選択リスト
        private SelectList CompanyStatusSelectList;
        // CompanyStatusをキーとしたDescriptionの連想配列
        private Dictionary<int, string> CompanyStatuses;

        public ClientCompanyController( SampleCRMContext sampleCRMContext )
        {
            SampleCRMContext = sampleCRMContext;

            // 会社状態のSelectListを作成
            string description;
            CompanyStatuses = new Dictionary<int, string>();

            foreach ( var status in SampleCRMContext.CompanyStatuses )
            {
                if ( status.CompanyStatusName == "営業会社" )
                {
                    continue; // 「営業会社」なので選択リストに追加する必要がない
                }

                description = status.CompanyStatusName;
                CompanyStatuses.Add( status.CompanyStatusCode, description );
            }

            CompanyStatusSelectList = new SelectList( CompanyStatuses.Values.ToList() );
        }

        // GET: ClientCompany
        public async Task<IActionResult> Index( int? page = 1, string searchWord = "" )
        {
            try
            {
                var stopwatch = new Stopwatch();

                // 計測開始
                stopwatch.Start();

                // 'page'が１未満の場合は404を返す。
                if ( page < 1 )
                {
                    return NotFound();
                }

                // 顧客会社一覧を取得開始
                IQueryable<Company>? filteredRecords;

                // 検索キーワードを元に検索を行う
                if ( searchWord.IsNullOrEmpty() )
                {
                    // 「検索キーワード」欄が空欄の場合
                    filteredRecords = SampleCRMContext.Companies;
                }
                else
                {
                    filteredRecords = ( CookieUtility.GetEnumValueFromCookie<SearchMethod>( Request ) switch
                    {
                        // 「会社名カナ」
                        SearchMethod.CompanyNameKana
                            => SampleCRMContext.Companies
                                .Where( x => x.PhoneticName.Contains( searchWord ) ),

                        // 「部署名」
                        SearchMethod.DepartmentName
                            => SampleCRMContext.GetJoinnedCompaniesWithDepartments()
                                .Where( x => x.Department.DepartmentName.Contains( searchWord )
                                            || x.Department.DetailedDepartmentName.Contains( searchWord ) )
                                .Select( x => x.Company ),

                        // 「部署名カナ」
                        SearchMethod.DepartmentNameKana
                            => SampleCRMContext.GetJoinnedCompaniesWithDepartments()
                                .Where( x => x.Department.PhoneticName.Contains( searchWord ) )
                                .Select( x => x.Company ),

                        // 「電話番号」
                        SearchMethod.PhoneNumber
                            => SampleCRMContext.GetJoinnedCompaniesWithEmployees()
                                .Where( x => x.Department.TelNumber.Contains( searchWord )
                                            || x.Department.FaxNumber.Contains( searchWord )
                                            || x.Employee.CellPhoneNumber.Contains( searchWord ) )
                                .Select( x => x.Company ),

                        // 「会社名」(何らかの理由でCookieがNullの場合もこちら)
                        SearchMethod.CompanyName or _
                            => SampleCRMContext.Companies
                                .Where( x => x.CompanyName.Contains( searchWord ) ),

                    } ).Distinct(); // 検索の過程で発生した重複を削除(「部署」や「担当者」テーブルがJoinされた場合に発生)
                }

                // 顧客会社かつ論理削除されていないもののみにする。
                filteredRecords = filteredRecords.Where( x => x.IsClientCompany && x.DeleteDate == DateTime.MaxValue );

                // 会社状態
                int selectedCompanyStatusCode;
                if ( CookieUtility.GetValueFromCookie( Request, $"Selected{nameof( CompanyStatus )}" ) is { } selectedCompanyStatus
                    && !string.IsNullOrEmpty( selectedCompanyStatus ) // 「全て」が選択されているかどうかをこちらで確認している
                    && int.TryParse( selectedCompanyStatus, out selectedCompanyStatusCode ) )
                {
                    filteredRecords = filteredRecords.Where( x => x.CompanyStatusCode == selectedCompanyStatusCode );
                }

                // 会社コードの昇順・降順
                filteredRecords = CookieUtility.GetEnumValueFromCookie<CompanyCodeOrder>( Request ) switch
                {
                    CompanyCodeOrder.DESC => filteredRecords.OrderByDescending( x => x.CompanyCode ),

                    // CookieがNullなら(シークレットモードの場合とか？)取り敢えず昇順で表示する。適当
                    CompanyCodeOrder.ASC or _ => filteredRecords.OrderBy( x => x.CompanyCode ),
                };

                // 以上の検索条件・表示条件を元にDBアクセスを行う
                var companies = await filteredRecords
                    .ToPagedListAsync(
                    page!.Value,
                    CookieUtility.GetEnumValueFromCookie<DisplayCountPerPage>( Request ).GetValueOrDefault( DisplayCountPerPage.UpTo20 ).GetHashCode() );

                // 指定したページが全ページ数を超えている場合は404を返す。(special case first page if no items exist)
                if ( companies.PageNumber != 1 && page > companies.PageCount )
                {
                    return NotFound();
                }

                ViewBag.Companies = companies;

                var viewModels = new List<ClientCompanyCommonViewModel>();
                foreach ( var company in companies )
                {
                    var viewModel = new ClientCompanyCommonViewModel(
                        company,
                        await SampleCRMContext.Departments
                                .Where( x => x.CompanyCode == company.CompanyCode && x.IsMain ) // 部署情報は代表部署だけを取得する
                                .SingleOrDefaultAsync() );

                    viewModel.CompanyStatus = await SampleCRMContext.GetCompanyStatusNameAsync( company.CompanyStatusCode );

                    viewModel.SystemKinds = string.Join(
                        ",",
                        ( await SampleCRMContext.GetActiveContractListByCompanyCodeAsync( company.CompanyCode ) )
                            .OrderBy( x => x.SystemKindName )
                            .Select( x => x.SystemKindName )
                            .Distinct() );

                    viewModels.Add( viewModel );
                }

                // 計測終了
                stopwatch.Stop();

                // 結果表示
                Console.WriteLine( $"処理時間: {stopwatch.ElapsedMilliseconds} ms" );

                return View( viewModels );
            }
            catch ( Exception ex )
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult Search( string searchword, SearchMethod searchMethod, int? page = 1 )
        {
            // 検索方法をCookieに保存
            CookieUtility.SaveEnumValueToCookie( Response, searchMethod );

            // Indexアクションメソッドと同じ処理を実行
            return RedirectToAction( nameof( Index ), new { page, searchword } );
        }

        [HttpPost]
        public IActionResult SwitchCompanyCodeOrder( string searchword, CompanyCodeOrder companyCodeOrder, int? page = 1 )
        {
            // 検索方法をCookieに保存
            CookieUtility.SaveEnumValueToCookie( Response, companyCodeOrder );

            // Indexアクションメソッドと同じ処理を実行
            return RedirectToAction( nameof( Index ), new { page, searchword } );
        }

        [HttpPost]
        public IActionResult FilterCompanyStatus( string searchword, int? selectedCompanyStatusCode, int? page = 1 )
        {
            // 検索方法をCookieに保存
            CookieUtility.SaveValueToCookie(
                Response,
                $"Selected{nameof( CompanyStatus )}",
                ( selectedCompanyStatusCode is null ) switch
                {
                    // 「全て」が選択されている場合を想定
                    true => string.Empty,

                    false => selectedCompanyStatusCode.ToString(),
                } );

            // Indexアクションメソッドと同じ処理を実行
            return RedirectToAction( nameof( Index ), new { page, searchword } );
        }

        [HttpPost]
        public IActionResult ChangeDisplayCount( string searchword, DisplayCountPerPage displayCount, int? page = 1 )
        {
            // 検索方法をCookieに保存
            CookieUtility.SaveEnumValueToCookie( Response, displayCount );

            // Indexアクションメソッドと同じ処理を実行
            return RedirectToAction( nameof( Index ), new { page, searchword } );
        }

        // 詳細ページだが部署一覧も兼ねている
        // GET: ClientCompany/Details/5
        public async Task<IActionResult> Details( int? id )
        {
            // 会社、部署、担当者の取得
            if ( id is null || await SampleCRMContext.Companies.FindAsync( id ) is not { } company )
            {
                return NotFound();
            }

            var viewModel = new ClientCompanyCommonViewModel( company );

            viewModel.CompanyStatus = await SampleCRMContext.GetCompanyStatusNameAsync( company.CompanyStatusCode );

            // 部署情報取得

SampleCRM/SampleCRM/Views/ClientDepartment/Create.cshtml
@model SampleCRM.Models.ViewModels.ClientDepartmentViewModel

@{
    ViewData["Title"] = "契約部署追加";
}

<h1>部署追加</h1>
<h5>@Model.CompanyName</h5>
<div class="form-group">
    <label class="control-label"><label class="control-label"><span style="color:#ff0000;">※</span></label>は必須入力項目です。</label>
</div>
<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="Create" class="h-adr">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompanyCode" />
            <input type="hidden" asp-for="EditableMainDepartment" />
            <div class="form-group form-check">
                @if (Model.EditableMainDepartment)
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" />@Html.DisplayNameFor(model => model.IsMainDepartment)
                    </label>
                }
                else
                {
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsMainDepartment" disabled="disabled" />既に代表部署が登録されているので設定できません
                    </label>
                }
            </div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label><label class="control-label"><span style="color:#ff0000;">※</span></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentPhoneticName" class="control-label"></label>
                <input asp-for="DepartmentPhoneticName" class="form-control" />
                <span asp-validation-for="DepartmentPhoneticName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentPostalCode" class="control-label"></label>
                <input type="hidden" class="p-country-name" value="Japan" />
                <input asp-for="DepartmentPostalCode" class="form-control p-postal-code" />
                <button type="button" class="btn-secondary postal-search">郵便番号から住所を検索する</button>
                <span asp-validation-for="DepartmentPostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentAddress" class="control-label"></label>
                <input asp-for="DepartmentAddress" class="form-control p-region p-locality p-street-address p-extended-address" />
                <span asp-validation-for="DepartmentAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentTelNumber" class="control-label"></label>
                <input asp-for="DepartmentTelNumber" class="form-control" />
                <span asp-validation-for="DepartmentTelNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentFaxNumber" class="control-label"></label>
                <input asp-for="DepartmentFaxNumber" class="form-control" />
                <span asp-validation-for="DepartmentFaxNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentEmail" class="control-label"></label>
                <input asp-for="DepartmentEmail" class="form-control" />
                <span asp-validation-for="DepartmentEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <textarea asp-for="Note" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeName" class="control-label"></label><label class="control-label"><span style="color:#ff0000;">※</span></label>
                <input asp-for="EmployeeName" class="form-control" />
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeePhoneticName" class="control-label"></label>
                <input asp-for="EmployeePhoneticName" class="form-control" />
                <span asp-validation-for="EmployeePhoneticName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeePosition" class="control-label"></label>
                <input asp-for="EmployeePosition" class="form-control" />
                <span asp-validation-for="EmployeePosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeTelNumber" class="control-label"></label>
                <input asp-for="EmployeeTelNumber" class="form-control" />
                <span asp-validation-for="EmployeeTelNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeEmail" class="control-label"></label>
                <input asp-for="EmployeeEmail" class="form-control" />
                <span asp-validation-for="EmployeeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeSNS" class="control-label"></label>
                <input asp-for="EmployeeSNS" class="form-control" />
                <span asp-validation-for="EmployeeSNS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="追加" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="ClientCompany" asp-action="Details" asp-route-id="@Model.CompanyCode">契約会社詳細へ</a>
</div>

SampleCRM/SampleCRM/Views/ClientDepartment/Delete.cshtml
@model SampleCRM.Models.ViewModels.ClientDepartmentViewModel
@{
    ViewData["Title"] = "部署削除";
}

<h1>部署削除</h1>
<br />
<b>この部署を削除しますか？</b>
<div>※注意：ライセンス情報を登録している場合は、先にそちらを削除してください。</div>
<div>　　　　また、削除後は復旧できません。</div>
<div>
    <hr />
    <dl class="row">
        <!-- 会社情報 -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.CompanyName)
                <rt>@Html.DisplayFor(model => model.CompanyPhoneticName)</rt>
            </ruby>
        </dd>

        <!-- 部署情報 -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class="col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.DepartmentName)
                <rt>@Html.DisplayFor(model => model.DepartmentPhoneticName)</rt>
            </ruby>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsMainDepartment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsMainDepartment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentPostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentPostalCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentTelNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentTelNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentFaxNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentFaxNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEmail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEmail)
        </dd>

        <!-- 担当者情報 -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>
        <dd class="col-sm-10">
            <ruby>
                @Html.DisplayFor(model => model.EmployeeName)
                <rt>@Html.DisplayFor(model => model.EmployeePhoneticName)</rt>
            </ruby>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeePosition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeePosition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeTelNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeTelNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeEmail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeEmail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeSNS)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeSNS)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="DepartmentCode" />
        <input type="submit" value="削除" class="btn btn-danger" /> |
        <a asp-controller="ClientCompany" asp-action="Details" asp-route-id="@Model?.CompanyCode">契約会社一覧へ</a>
    </form>
</div>

SampleCRM/SampleCRM/Views/ClientDepartment/Index.cshtml
@model IEnumerable<SampleCRM.Models.TableModels.Department>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">新規作成</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IsMain)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneticName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaxNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IsMain)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneticName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostalCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TelNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FaxNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.DepartmentCode">編集</a> |
                    <a asp-action="Details" asp-route-id="@item.DepartmentCode">詳細</a> |
                    <a asp-action="Delete" asp-route-id="@item.DepartmentCode">削除</a>
                </td>
            </tr>
        }
    </tbody>
</table>